apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scoreboardfrontend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: scoreboardfrontend
    spec:
      containers:
      - name: scoreboardfrontend
        image: eu.gcr.io/rollasphere/rollaspherefrontend
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m      