apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ghostservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ghostservice
    spec:
      containers:
      - name: ghostservice
        image: eu.gcr.io/rollasphere/ghostservice
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m      