apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cheatservice
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cheatservice
    spec:
      containers:
      - name: cheatservice
        image: eu.gcr.io/rollasphere/cheatservice
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m      